name: devspace-cloud
version: 0.0.3
commands:
  - name: "login"
    baseArgs: ["login"]
  - name: "create"
    baseArgs: ["create"]
  - name: "connect"
    baseArgs: ["connect"]
  - name: "provider"
    baseArgs: ["add", "provider"]
    subCommand: "add"
  - name: "providers"
    baseArgs: ["list", "providers"]
    subCommand: "list"
  - name: "spaces"
    baseArgs: ["list", "spaces"]
    subCommand: "list"
  - name: "clusters"
    baseArgs: ["list", "clusters"]
    subCommand: "list"
  - name: "provider"
    baseArgs: ["remove", "provider"]
    subCommand: "remove"
  - name: "space"
    baseArgs: ["remove", "space"]
    subCommand: "remove"
  - name: "cluster"
    baseArgs: ["remove", "cluster"]
    subCommand: "remove"
  - name: "key"
    baseArgs: ["reset", "key"]
    subCommand: "reset"
  - name: "encryptionkey"
    baseArgs: ["set", "encryptionkey"]
    subCommand: "set"
  - name: "provider"
    baseArgs: ["use", "provider"]
    subCommand: "use"
  - name: "space"
    baseArgs: ["use", "space"]
    subCommand: "use"
hooks:
  - event: analyze
    baseArgs: ["resume", "space"]
  - event: attach
    baseArgs: ["resume", "space"]
  - event: deploy
    baseArgs: ["resume", "space"]
  - event: dev
    baseArgs: ["resume", "space"]
  - event: enter
    baseArgs: ["resume", "space"]
  - event: logs
    baseArgs: ["resume", "space"]
  - event: open
    baseArgs: ["resume", "space"]
  - event: purge
    baseArgs: ["resume", "space"]
  - event: sync
    baseArgs: ["resume", "space"]
vars:
  - name: DEVSPACE_SPACE
    baseArgs: ["vars", "space"]
  - name: DEVSPACE_SPACE_NAMESPACE
    baseArgs: ["vars", "space-namespace"]
  - name: DEVSPACE_USERNAME
    baseArgs: ["vars", "username"]
binaries:
  - os: darwin
    arch: amd64
    path: https://github.com/devspace-cloud/devspace-cloud-plugin/releases/download/v0.0.2/devspace-cloud-plugin-darwin-amd64
  - os: linux
    arch: amd64
    path: https://github.com/devspace-cloud/devspace-cloud-plugin/releases/download/v0.0.2/devspace-cloud-plugin-linux-amd64
  - os: linux
    arch: "386"
    path: https://github.com/devspace-cloud/devspace-cloud-plugin/releases/download/v0.0.2/devspace-cloud-plugin-linux-386
  - os: windows
    arch: amd64
    path: https://github.com/devspace-cloud/devspace-cloud-plugin/releases/download/v0.0.2/devspace-cloud-plugin-windows-amd64.exe
  - os: windows
    arch: "386"
    path: https://github.com/devspace-cloud/devspace-cloud-plugin/releases/download/v0.0.2/devspace-cloud-plugin-windows-386.exe
